version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - VITE_OLLAMA_API_URL=http://ollama:11434
    container_name: app

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    container_name: ollama
    volumes:
      - ./ollama-data:/root/.ollama

volumes:
  ollama-data:
